### ISSUE TITLE
Lead Page image carousel controls no working and formatting problems

### ISSUE THREAD

**Issue by christophersw** [esrgc/Firstnet#1]
The lead page carousel controls are not working properly. Furthermore, the carousel seems to have some formatting issues. Both of these problems might be a result of the new images being non-uniform in size. We need to either change the carousel to allow for the new images, or assign the generation of new images to Chris.

**Comment by tahoang** [comment]
@christophersw the problem with the carousel is that all the images are not in the same height. I can fix it by changing the css style for the images to make them have the same height. However, that would make the images look unnatural. The best way to fix this is you can resize/crop the images to have the same height. For example, 600px.

**Comment by christophersw** [comment]
We will recut the graphics to a uniform height.
